# Generated by Django 2.2.1 on 2020-02-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200203_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
